name: Deploy Maven

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    uses: eclipse-daanse/.github/.github/workflows/reuse_java_deploy.yml@main
    secrets: inherit


  docker_build:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

      - name: Update dockerhub repo description
        uses: peter-evans/dockerhub-description@432a30c9e07499fd01da9f8a49f0faf9e0ca5b77 # v4.0.2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: eclipsedaanse/probe
          readme-filepath: application/probe/container/README.md

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.2.1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to Docker Hub
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to Github Docker Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Multi-Arch Docker Image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: "application/probe/container/Dockerfile"
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8,linux/386,linux/riscv64
          push: true
          tags: |
            docker.io/eclipsedaanse/probe:snapshot
            docker.io/eclipsedaanse/probe:${{ github.sha }}
            ghcr.io/eclipse-daanse/probe:snapshot
            ghcr.io/eclipse-daanse/probe:${{ github.sha }}


